### PR TITLE
Dummy app panel

### PR DESCRIPTION
**Pull request by Tianhao-Gu**
Screen Shot 2019-05-20 at 3 00 14 PM

### CODE REVIEW

**Comment by Tianhao-Gu** [comment]
@briehl Getting dummy app info displayed. Will start working on building appcard.

**Comment by Tianhao-Gu** [comment]
Screen Shot 2019-05-20 at 2 01 35 PM

**Comment by Tianhao-Gu** [comment]
Screen Shot 2019-05-20 at 3 00 14 PM

**Comment by briehl** [comment]
👍

**Pull request merged**
